"""add due_date notes and manual_order to tasks

Revision ID: b8404f65f979
Revises: 20251220_104402
Create Date: 2025-12-21 10:40:28.787526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8404f65f979'
down_revision: Union[str, Sequence[str], None] = '20251220_104402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM types for status and priority
    task_status_enum = postgresql.ENUM('PENDING', 'COMPLETED', name='taskstatus')
    task_status_enum.create(op.get_bind(), checkfirst=True)

    task_priority_enum = postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='taskpriority')
    task_priority_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('view_preferences',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preference_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('preference_value', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'preference_key', name='uq_user_preference_key')
    )
    op.create_index(op.f('ix_view_preferences_preference_key'), 'view_preferences', ['preference_key'], unique=False)
    op.create_index(op.f('ix_view_preferences_user_id'), 'view_preferences', ['user_id'], unique=False)
    # Add new columns for extended task functionality
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('notes', sa.TEXT(), nullable=True))
    op.add_column('tasks', sa.Column('manual_order', sa.Integer(), nullable=True))

    # Skip enum conversion and index changes - keep existing VARCHAR types
    # These will be handled in a future migration if needed
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove new columns
    op.drop_column('tasks', 'manual_order')
    op.drop_column('tasks', 'notes')
    op.drop_column('tasks', 'due_date')

    # Drop view_preferences table
    op.drop_index(op.f('ix_view_preferences_user_id'), table_name='view_preferences')
    op.drop_index(op.f('ix_view_preferences_preference_key'), table_name='view_preferences')
    op.drop_table('view_preferences')

    # Drop ENUM types
    postgresql.ENUM(name='taskstatus').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='taskpriority').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
