openapi: 3.1.0
info:
  title: Subtasks API
  version: 1.0.0
  description: Subtask management endpoints for breaking down tasks into smaller steps

paths:
  /api/v1/tasks/{task_id}/subtasks:
    get:
      summary: List all subtasks for a task
      operationId: listSubtasks
      tags:
        - subtasks
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of subtasks
          content:
            application/json:
              schema:
                type: object
                properties:
                  subtasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Subtask'
                  total:
                    type: integer
                  completed:
                    type: integer
                  progress_percentage:
                    type: number
                    format: float
                    minimum: 0
                    maximum: 100
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

    post:
      summary: Create a new subtask
      operationId: createSubtask
      tags:
        - subtasks
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubtaskCreate'
      responses:
        '201':
          description: Subtask created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subtask'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

  /api/v1/subtasks/{subtask_id}:
    get:
      summary: Get a specific subtask by ID
      operationId: getSubtask
      tags:
        - subtasks
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/SubtaskId'
      responses:
        '200':
          description: Subtask details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subtask'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

    patch:
      summary: Update a subtask
      operationId: updateSubtask
      tags:
        - subtasks
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/SubtaskId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubtaskUpdate'
      responses:
        '200':
          description: Subtask updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subtask'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

    delete:
      summary: Delete a subtask
      operationId: deleteSubtask
      tags:
        - subtasks
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/SubtaskId'
      responses:
        '204':
          description: Subtask deleted successfully
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

  /api/v1/subtasks/{subtask_id}/toggle:
    patch:
      summary: Toggle subtask completion status
      operationId: toggleSubtask
      tags:
        - subtasks
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/SubtaskId'
      responses:
        '200':
          description: Subtask toggled successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  subtask:
                    $ref: '#/components/schemas/Subtask'
                  parent_task_updated:
                    type: boolean
                    description: Whether parent task was auto-completed
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

  /api/v1/tasks/{task_id}/subtasks/reorder:
    patch:
      summary: Reorder subtasks for a task
      operationId: reorderSubtasks
      tags:
        - subtasks
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subtask_order:
                  type: array
                  items:
                    type: string
                    format: uuid
                  minItems: 1
                  description: Ordered array of subtask IDs
              required:
                - subtask_order
      responses:
        '200':
          description: Subtasks reordered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  subtasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Subtask'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    SubtaskId:
      name: subtask_id
      in: path
      required: true
      description: The unique identifier of the subtask
      schema:
        type: string
        format: uuid

  schemas:
    Subtask:
      type: object
      properties:
        id:
          type: string
          format: uuid
        task_id:
          type: string
          format: uuid
        description:
          type: string
          minLength: 1
          maxLength: 200
        is_completed:
          type: boolean
        order_index:
          type: integer
          minimum: 0
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - task_id
        - description
        - is_completed
        - order_index
        - created_at
        - updated_at

    SubtaskCreate:
      type: object
      properties:
        description:
          type: string
          minLength: 1
          maxLength: 200
          example: 'Review pull request'
        order_index:
          type: integer
          minimum: 0
          description: Position in the subtask list (auto-assigned if not provided)
      required:
        - description

    SubtaskUpdate:
      type: object
      properties:
        description:
          type: string
          minLength: 1
          maxLength: 200
        is_completed:
          type: boolean
        order_index:
          type: integer
          minimum: 0
      minProperties: 1

    Error:
      type: object
      properties:
        detail:
          type: string
        errors:
          type: array
          items:
            type: string
      required:
        - detail

  responses:
    UnauthorizedError:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFoundError:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    ValidationError:
      description: Validation failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
