openapi: 3.1.0
info:
  title: Tags API
  version: 1.0.0
  description: Tag management endpoints for task categorization and filtering

paths:
  /api/v1/tags:
    get:
      summary: List all tags for the authenticated user
      operationId: listTags
      tags:
        - tags
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of tags
          content:
            application/json:
              schema:
                type: object
                properties:
                  tags:
                    type: array
                    items:
                      $ref: '#/components/schemas/Tag'
                  total:
                    type: integer
                    description: Total number of tags
        '401':
          $ref: '#/components/responses/UnauthorizedError'

    post:
      summary: Create a new tag
      operationId: createTag
      tags:
        - tags
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagCreate'
      responses:
        '201':
          description: Tag created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '409':
          description: Tag name already exists for this user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/tags/{tag_id}:
    get:
      summary: Get a specific tag by ID
      operationId: getTag
      tags:
        - tags
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/TagId'
      responses:
        '200':
          description: Tag details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

    patch:
      summary: Update a tag
      operationId: updateTag
      tags:
        - tags
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/TagId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagUpdate'
      responses:
        '200':
          description: Tag updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '409':
          description: Tag name already exists for this user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete a tag
      operationId: deleteTag
      tags:
        - tags
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/TagId'
      responses:
        '204':
          description: Tag deleted successfully
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

  /api/v1/tasks/{task_id}/tags:
    post:
      summary: Add tags to a task
      operationId: addTagsToTask
      tags:
        - tags
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tag_ids:
                  type: array
                  items:
                    type: string
                    format: uuid
                  minItems: 1
              required:
                - tag_ids
      responses:
        '200':
          description: Tags added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  task_id:
                    type: string
                    format: uuid
                  tags:
                    type: array
                    items:
                      $ref: '#/components/schemas/Tag'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

    delete:
      summary: Remove tags from a task
      operationId: removeTagsFromTask
      tags:
        - tags
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tag_ids:
                  type: array
                  items:
                    type: string
                    format: uuid
                  minItems: 1
              required:
                - tag_ids
      responses:
        '200':
          description: Tags removed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  task_id:
                    type: string
                    format: uuid
                  tags:
                    type: array
                    items:
                      $ref: '#/components/schemas/Tag'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    TagId:
      name: tag_id
      in: path
      required: true
      description: The unique identifier of the tag
      schema:
        type: string
        format: uuid

  schemas:
    Tag:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 1
          maxLength: 50
        color:
          type: string
          pattern: '^#[0-9A-Fa-f]{6}$'
          example: '#3b82f6'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - user_id
        - name
        - color
        - created_at
        - updated_at

    TagCreate:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 50
          example: 'Work'
        color:
          type: string
          pattern: '^#[0-9A-Fa-f]{6}$'
          example: '#3b82f6'
          default: '#3b82f6'
      required:
        - name

    TagUpdate:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 50
        color:
          type: string
          pattern: '^#[0-9A-Fa-f]{6}$'
      minProperties: 1

    Error:
      type: object
      properties:
        detail:
          type: string
        errors:
          type: array
          items:
            type: string
      required:
        - detail

  responses:
    UnauthorizedError:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFoundError:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    ValidationError:
      description: Validation failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
